// The geniana command generates the internal IANA timezone catalog.
package main

import (
	"bufio"
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

func main() {
	var zoneTabPath string
	var versionFilePath string
	var version string
	var outPath string
	flag.StringVar(&zoneTabPath, "zone-tab", "", "path to IANA zone.tab")
	flag.StringVar(&versionFilePath, "version-file", "", "path to tzdb +VERSION file")
	flag.StringVar(&version, "version", "", "IANA tzdb version; overrides -version-file")
	flag.StringVar(&outPath, "out", "internal/zone/catalog.go", "output Go file")
	flag.Parse()

	if err := run(zoneTabPath, versionFilePath, version, outPath); err != nil {
		fmt.Fprintf(os.Stderr, "geniana: %v\n", err)
		os.Exit(1)
	}
}

func run(zoneTabPath, versionFilePath, version, outPath string) error {
	if zoneTabPath == "" {
		return errors.New("-zone-tab is required")
	}
	if version == "" {
		var err error
		version, err = readVersion(versionFilePath)
		if err != nil {
			return err
		}
	}
	zones, err := readZoneTab(zoneTabPath)
	if err != nil {
		return err
	}
	src, err := render(version, zoneTabPath, zones)
	if err != nil {
		return err
	}
	return os.WriteFile(outPath, src, 0o644) //nolint:gosec // Generated Go source should use normal repository file permissions.
}

func readVersion(path string) (string, error) {
	if path == "" {
		return "", errors.New("-version or -version-file is required")
	}
	b, err := os.ReadFile(path) //nolint:gosec // The caller intentionally selects the local tzdb version file.
	if err != nil {
		return "", fmt.Errorf("read version file: %w", err)
	}
	version := strings.TrimSpace(string(b))
	if version == "" {
		return "", fmt.Errorf("version file %q is empty", path)
	}
	return version, nil
}

func readZoneTab(path string) (zones []string, err error) {
	f, err := os.Open(path) //nolint:gosec // The caller intentionally selects the local IANA zone.tab file.
	if err != nil {
		return nil, fmt.Errorf("open zone.tab: %w", err)
	}
	defer func() {
		if closeErr := f.Close(); err == nil && closeErr != nil {
			err = fmt.Errorf("close zone.tab: %w", closeErr)
		}
	}()

	seen := map[string]bool{"UTC": true}
	zones = []string{"UTC"}
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 3 {
			return nil, fmt.Errorf("invalid zone.tab line %q", line)
		}
		zone := fields[2]
		if seen[zone] {
			continue
		}
		seen[zone] = true
		zones = append(zones, zone)
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scan zone.tab: %w", err)
	}
	slices.Sort(zones)
	return zones, nil
}

func render(version, zoneTabPath string, zones []string) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by internal/zone/geniana; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: IANA tzdb %s %s.\n", version, filepath.Base(zoneTabPath))
	fmt.Fprintf(&b, "\npackage zone\n\n")
	fmt.Fprintf(&b, "// CatalogVersion is the IANA tzdb version used to generate Zones.\n")
	fmt.Fprintf(&b, "const CatalogVersion = %q\n\n", version)
	fmt.Fprintf(&b, "// Zones is a sorted list of IANA timezone identifiers embedded at build time.\n")
	fmt.Fprintf(&b, "// Callers must not mutate this slice.\n")
	fmt.Fprintf(&b, "var Zones = []string{\n")
	for _, zone := range zones {
		fmt.Fprintf(&b, "\t%q,\n", zone)
	}
	fmt.Fprintf(&b, "}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return src, nil
}
