// The genwindows command generates the Windows-to-IANA mapping from a pinned
// Unicode CLDR windowsZones.xml release.
//
// Regenerate with an explicitly downloaded release source, for example:
//
//	go run ./internal/zone/genwindows -xml /path/to/windowsZones.xml -cldr release-48-1 -out internal/zone/windows.go
package main

import (
	"bytes"
	"encoding/xml"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

type mapping struct {
	windows string
	iana    string
}

func main() {
	var xmlPath string
	var cldrRelease string
	var outPath string
	flag.StringVar(&xmlPath, "xml", "", "path to a pinned CLDR windowsZones.xml")
	flag.StringVar(&cldrRelease, "cldr", "", "exact CLDR release tag")
	flag.StringVar(&outPath, "out", "internal/zone/windows.go", "output Go file")
	flag.Parse()

	if err := run(xmlPath, cldrRelease, outPath); err != nil {
		fmt.Fprintf(os.Stderr, "genwindows: %v\n", err)
		os.Exit(1)
	}
}

func run(xmlPath, cldrRelease, outPath string) error {
	if xmlPath == "" {
		return errors.New("-xml is required")
	}
	if cldrRelease == "" {
		return errors.New("-cldr is required")
	}
	mappings, err := readMappings(xmlPath)
	if err != nil {
		return err
	}
	src, err := render(cldrRelease, filepath.Base(xmlPath), mappings)
	if err != nil {
		return err
	}
	if err := os.WriteFile(outPath, src, 0o644); err != nil { //nolint:gosec // Generated Go source uses repository file permissions.
		return fmt.Errorf("write generated source: %w", err)
	}
	return nil
}

func readMappings(path string) (mappings []mapping, err error) {
	f, err := os.Open(path) //nolint:gosec // The maintainer explicitly selects the pinned CLDR source.
	if err != nil {
		return nil, fmt.Errorf("open windowsZones.xml: %w", err)
	}
	defer func() {
		if closeErr := f.Close(); err == nil && closeErr != nil {
			err = fmt.Errorf("close windowsZones.xml: %w", closeErr)
		}
	}()

	return decodeMappings(f)
}

func decodeMappings(r io.Reader) ([]mapping, error) {
	var doc struct {
		XMLName      xml.Name `xml:"supplementalData"`
		WindowsZones struct {
			MapTimezones struct {
				Entries []struct {
					Other     string `xml:"other,attr"`
					Territory string `xml:"territory,attr"`
					Type      string `xml:"type,attr"`
				} `xml:"mapZone"`
			} `xml:"mapTimezones"`
		} `xml:"windowsZones"`
	}
	if err := xml.NewDecoder(r).Decode(&doc); err != nil {
		return nil, fmt.Errorf("decode XML: %w", err)
	}

	seen := make(map[string]bool)
	var mappings []mapping
	for _, entry := range doc.WindowsZones.MapTimezones.Entries {
		if entry.Other == "" {
			return nil, errors.New("mapZone missing other attribute")
		}
		if entry.Territory == "" {
			return nil, fmt.Errorf("mapZone %q missing territory attribute", entry.Other)
		}
		if entry.Type == "" {
			return nil, fmt.Errorf("mapZone %q missing type attribute", entry.Other)
		}
		if entry.Territory != "001" {
			continue
		}

		targets := strings.Fields(entry.Type)
		if len(targets) != 1 {
			return nil, fmt.Errorf("mapZone %q territory 001 must contain exactly one IANA target", entry.Other)
		}
		if seen[entry.Other] {
			return nil, fmt.Errorf("duplicate territory 001 mapping for %q", entry.Other)
		}
		seen[entry.Other] = true
		mappings = append(mappings, mapping{windows: entry.Other, iana: targets[0]})
	}
	if len(mappings) == 0 {
		return nil, errors.New("no territory 001 mappings found")
	}
	slices.SortFunc(mappings, func(a, b mapping) int { return strings.Compare(a.windows, b.windows) })
	return mappings, nil
}

func render(cldrRelease, sourcePath string, mappings []mapping) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by internal/zone/genwindows; DO NOT EDIT.")
	fmt.Fprintf(&b, "// Source: Unicode CLDR %s %s, territory %q.\n", cldrRelease, filepath.Base(sourcePath), "001")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "package zone")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// WindowsToIANA maps Windows timezone names to CLDR's territory 001 IANA defaults.")
	fmt.Fprintln(&b, "var WindowsToIANA = map[string]string{")
	for _, entry := range mappings {
		fmt.Fprintf(&b, "\t%q: %q,\n", entry.windows, entry.iana)
	}
	fmt.Fprintln(&b, "}")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return src, nil
}
