// Code generated by internal/zone/genwindows; DO NOT EDIT.
// Source: Unicode CLDR release-48-1 windowsZones.xml, territory "001".

package zone

// WindowsToIANA maps Windows timezone names to CLDR's territory 001 IANA defaults.
var WindowsToIANA = map[string]string{
	"Alpha Standard Time": "America/Godthab",
	"Zulu Standard Time":  "Etc/UTC",
}
