// Code generated by internal/zone/geniana; DO NOT EDIT.
// Source: IANA tzdb 2025b zone.tab.

package zone

// CatalogVersion is the IANA tzdb version used to generate Zones.
const CatalogVersion = "2025b"

// Zones is a sorted list of IANA timezone identifiers embedded at build time.
// Callers must not mutate this slice.
var Zones = []string{
	"America/New_York",
	"Europe/London",
	"UTC",
}
